baseurl = "/"
languageCode = "en-us"
title = "Bloomington Playwrights Project"

[[menu.main]]
  name = "Home"
  pre = "<i class='fa fa-download'></i>"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Shows"
  pre = "<i class='fa fa-download'></i>"
  url = "/show"
  weight = -200
[[menu.main]]
  name = "Tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "/tickets"
  identifier = "tickets"
  weight = -180
[[menu.main]]
  name = "OvationTix"
  parent = "tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "https://web.ovationtix.com/trs/dept/1090"
  weight = -180

preserveTaxonomyNames = true

[taxonomies]
genre = "genres" # drama, musical, etc
series = "series" # a run of plays; year1-year2
actor = "actors"
playwright = "playwrights"
director = "directors"
musician = "musicians"
lyricist = "lyricists"
