baseurl = "http://bppwrite.github.io/"
languageCode = "en-us"
googleAnalytics = "UA-35759378-1"

title = "Bloomington Playwrights Project"

preserveTaxonomyNames = true

[taxonomies]
genre = "genres" # drama, musical, etc
series = "series" # a run of plays; formatted as year1-year2
actor = "actors"
playwright = "playwrights"
director = "directors"
musician = "musicians"
lyricist = "lyricists"
# choreographer = "choreographers"
# "stage manager" = "stage managers"
# "lighting designer" = "lighting designers"
# "set designer" = "set designers"
# "costume designer" = "costume designers"
# "sound designer" = "sound designers"
award = "awards"
venue = "venues"

[params]
    [params.address]
        street = "107 West 9th Street"
        city = "Bloomington"
        state = "IN"
        zip = "40404"
        phone = "812.334.1188"
        email = "bppwrite@newplays.org"
    [params.social]
        github          = "bppwrite"
        facebook        = "BloomingtonPlaywrightsProject"
        facebook_app_id = "1810257965898767"
        twitter         = "bloomingplays"
        twitter_domain  = "" # This domain shows in twitter cards as "View on `twitter_domain`"
        googleplus      = ""
        pinterest       = "bloomingplays"
        instagram       = "bloomingplays"
        youtube         = "UCHUgE7KH1bGDoPRiHv1H1VA"
        linkedin        = "bloomington-playwrights-project"
# [params]
#     currentSeries = "2016-2017"

[[menu.main]]
    name = "Season" # - Plays and events listed chronologically – like ATF’s site is fine – denoting which is a show and which is a special event - Sub-pages for each show
    url = "/season/" # dynamically set to the current series
    pre = "hero" # hack -- using pre to indicate that this is a hero menu item
    weight = 100
[[menu.main]]
    name = "Tickets"
    url = "/tickets/"
    weight = 200
[[menu.main]]
    name = "Education" #(page and link for each of the following)
    url = "/education/"
    identifier = "education"
    weight = 300
[[menu.main]]
    name = "Broadway Kids"
    url = "/education/broadway-kids/"
    parent = "education"
    weight = 310
[[menu.main]]
    name = "DramatiCATS"
    url = "/education/dramaticats/"
    parent = "education"
    weight = 320
[[menu.main]]
    name = "Laugh Factory"
    url = "/education/laugh-factory/"
    parent = "education"
    weight = 330
[[menu.main]]
    name = "Musical Theater Camp"
    url = "/education/musical-theater-camp/"
    parent = "education"
    weight = 340
[[menu.main]]
    name = "After School Edventures"
    url = "/education/after-school-edventures/"
    parent = "education"
    weight = 350
[[menu.main]]
    name = "MiniPlay Playwriting Contest"
    url = "/education/miniplay-playwriting-contest/"
    parent = "education"
    weight = 360
[[menu.main]]
    name = "Playwrights"
    url = "/submit-a-play/"
    identifier = "playwrights"
    pre = "hero" # hack -- using pre to indicate that this is a hero menu item
    weight = 400
[[menu.main]]
    name = "Alumni Playwrights"
    url = "/submit-a-play/#alumni-playwrights"
    parent = "playwrights"
    weight = 410
[[menu.main]]
    name = "Submit a Play"
    url = "/submit-a-play/#submit-a-play"
    parent = "playwrights"
    weight = 420
[[menu.main]]
    name = "Reva Shiner Comedy Award"
    url = "/submit-a-play/reva-shiner-comedy/"
    parent = "playwrights"
    weight = 430
[[menu.main]]
    name = "Woodward/Newman Drama Award"
    url = "/submit-a-play/woodward-newman-drama/"
    parent = "playwrights"
    weight = 440
[[menu.main]]
    name = "Photo Gallery"
    url = "/photo-gallery/"
    weight = 500
[[menu.main]]
    name = "Get Involved"
    url = "/get-involved/"
    identifier = "get-involved"
    pre = "hero" # hack -- using pre to indicate that this is a hero menu item
    weight = 600
[[menu.main]]
    name = "Volunteer"
    url = "/get-involved/#volunteer"
    parent = "get-involved"
    weight = 610
[[menu.main]]
    name = "Auditions"
    url = "/get-involved/#auditions"
    parent = "get-involved"
    weight = 620
[[menu.main]]
    name = "Technical Opportunities"
    url = "/get-involved/#technical-opportunities"
    parent = "get-involved"
    weight = 630
[[menu.main]]
    name = "Support"
    url = "/support/"
    identifier = "support"
    weight = 700
# [[menu.main]]
#     name = "Individual"
#     url = "/support/#individual"
#     parent = "support"
#     weight = 710
# [[menu.main]]
#     name = "Corporate"
#     url = "/support/#corporate"
#     parent = "support"
#     weight = 720
[[menu.main]]
    name = "Facility Rentals"
    url = "/facility-rentals/"
    weight = 800
[[menu.main]]
    name = "About Us"
    url = "/about/"
    identifier = "about"
    weight = 900
[[menu.main]]
    name = "Staff"
    url = "/about/#staff"
    parent = "about"
    weight = 910
[[menu.main]]
    name = "Board of Directors"
    url = "/about/#board-of-directors"
    parent = "about"
    weight = 920
[[menu.main]]
    name = "Director's Circle"
    url = "/about/#director-s-circle"
    parent = "about"
    weight = 930
[[menu.main]]
    name = "Mission & History"
    url = "/about/#mission-history"
    parent = "about"
    weight = 940
[[menu.main]]
    name = "Past Productions"
    url = "/about/#past-productions"
    parent = "about"
    weight = 950
[[menu.main]]
    name = "Arts Fair on the Square"
    url = "/about/#arts-fair-on-the-square"
    parent = "about"
    weight = 960
[[menu.main]]
    name = "Facility Rentals"
    url = "/facility-rentals/"
    pre = "foot"
    weight = 1000
[[menu.main]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    pre = "foot"
    weight = 1100
[[menu.main]]
    name = "Terms & Conditions"
    url = "/terms-and-conditions/"
    pre = "foot"
    weight = 1200
[[menu.main]]
    name = "Contact Us"
    url = "/contact"
    pre = "foot"
    weight = 1300
