baseurl = "/"
languageCode = "en-us"
title = "Bloomington Playwrights Project"

[[menu.main]]
  name = "Shows"
  pre = "<i class='fa fa-download'></i>"
  url = "/show"
  weight = -200
[[menu.main]]
  name = "Tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "/tickets"
  identifier = "tickets"
  weight = -180
[[menu.main]]
  name = "OvationTix"
  parent = "tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "https://web.ovationtix.com/trs/dept/1090"
  weight = -180
[[menu.main]]
  name = "Support"
  pre = "<i class='fa fa-download'></i>"
  url = "/support"
  weight = -200
[[menu.main]]
  name = "Join"
  pre = "<i class='fa fa-download'></i>"
  url = "/join"
  weight = -200
[[menu.main]]
  name = "About"
  pre = "<i class='fa fa-download'></i>"
  url = "/about"
  weight = -200
[[menu.main]]
  name = "Contact"
  pre = "<i class='fa fa-download'></i>"
  url = "/contact"
  weight = -200

preserveTaxonomyNames = true

[taxonomies]
genre = "genres" # drama, musical, etc
series = "series" # a run of plays; formatted as year1-year2
actor = "actors"
playwright = "playwrights"
director = "directors"
musician = "musicians"
lyricist = "lyricists"
choreographer = "choreographers"
award = "awards"
venue = "venues"
