baseurl = "/"
languageCode = "en-us"
title = "Bloomington Playwrights Project"

# [params]
#     currentSeries = "2016-2017"

[[menu.main]]
    name = "Shows"
    pre = "<i class='fa fa-download'></i>"
    url = "/show"
    weight = -200
[[menu.main]]
    name = "Events"
    pre = "<i class='fa fa-download'></i>"
    url = "/event"
    weight = -195
[[menu.main]]
  name = "Tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "/tickets"
  identifier = "tickets"
  weight = -210
[[menu.main]]
  name = "OvationTix"
  parent = "tickets"
  pre = "<i class='fa fa-cubes'></i>"
  url = "https://web.ovationtix.com/trs/dept/1090"
  weight = -210
[[menu.main]]
  name = "Support"
  pre = "<i class='fa fa-download'></i>"
  url = "/support"
  weight = -180
[[menu.main]]
  name = "Join"
  pre = "<i class='fa fa-download'></i>"
  url = "/join"
  weight = -190
[[menu.main]]
  name = "About"
  pre = "<i class='fa fa-download'></i>"
  url = "/about"
  weight = -160
[[menu.main]]
  name = "Blog"
  pre = "<i class='fa fa-download'></i>"
  url = "/contact"
  weight = -170

preserveTaxonomyNames = true

[taxonomies]
genre = "genres" # drama, musical, etc
series = "series" # a run of plays; formatted as year1-year2
actor = "actors"
playwright = "playwrights"
director = "directors"
musician = "musicians"
lyricist = "lyricists"
choreographer = "choreographers"
"stage manager" = "stage managers"
"lighting designer" = "lighting designers"
"set designer" = "set designers"
"costume designer" = "costume designers"
"sound designer" = "sound designers"
award = "awards"
venue = "venues"
