baseurl = "/"
languageCode = "en-us"
googleAnalytics = "UA-35759378-1"

title = "Bloomington Playwrights Project"

[params]
    [params.address]
        street = "107 West 9th Street"
        city = "Bloomington"
        state = "IN"
        zip = "40404"
        phone = "812.334.1188"
        email = "bppwrite@newplays.org"

# [params]
#     currentSeries = "2016-2017"

[[menu.main]]
    name = "Shows"
    url = "/show"
    weight = -200
[[menu.main]]
    name = "Events"
    url = "/event"
    weight = -195
[[menu.main]]
  name = "Tickets"
  url = "/tickets"
  identifier = "tickets"
  weight = -210
[[menu.main]]
  name = "OvationTix"
  parent = "tickets"
  url = "https://web.ovationtix.com/trs/dept/1090"
  weight = -210
[[menu.main]]
  name = "Support"
  url = "/support"
  weight = -180
[[menu.main]]
  name = "Join"
  url = "/join"
  weight = -190
[[menu.main]]
  name = "About"
  url = "/about"
  weight = -160
[[menu.main]]
  name = "Blog"
  url = "/contact"
  weight = -170

SectionPagesMenu = "main"

[[menu.foot]]
    name = "Contact"
    url = "/contact/"
    weight = 100
[[menu.foot]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 200
[[menu.foot]]
    name = "Terms & Conditions"
    url = "/terms-and-conditions/"
    weight = 300
[[menu.foot]]
    name = "Facility Rentals"
    url = "/facility-rentals/"
    weight = 400

preserveTaxonomyNames = true

[taxonomies]
genre = "genres" # drama, musical, etc
series = "series" # a run of plays; formatted as year1-year2
actor = "actors"
playwright = "playwrights"
director = "directors"
musician = "musicians"
lyricist = "lyricists"
choreographer = "choreographers"
"stage manager" = "stage managers"
"lighting designer" = "lighting designers"
"set designer" = "set designers"
"costume designer" = "costume designers"
"sound designer" = "sound designers"
award = "awards"
venue = "venues"
